### ISSUE TITLE
Implement validation of WordbreakRewriter configuration

### ISSUE THREAD

**Issue by ZenitK** [renekrie/querqy-elasticsearch#1]
https://github.com/renekrie/querqy-elasticsearch/blob/80f73e5932f293fcbc533edf8a0aff1678b74991/src/main/java/querqy/elasticsearch/rewriter/WordBreakRewriterFactory.java#L104

**Comment by renekrie** [comment]
The configuration can only check of a dictionaryField is configured but not if it exists in an index (even if we configured the field per index)
